### ISSUE TITLE
Inertial velocity used in aerodynamic drag calculation

### ISSUE THREAD

**Issue by olwyk** [Monash-HPR/Simulation#1]
Aerodynamics.getBodyForces() currently uses the inertial velocity vector in it's calculations, which leads to a large retarding force due to the eastward motion of the vehicle (matching the Earth's rotation). The State class methods for obtaining the velocity w.r.t the Earth frame are not working correctly, and are instead doubling the eastward velocity.

Consider renaming the State methods to clarify their frame, and review the calculations performed.

**Comment by Ciaran3105** [comment]
Recent push updated the inertial velocity to body velocity. State class methods still not working properly.
